### ISSUE TITLE
CPU usage not shared across multiple cores

### ISSUE THREAD

**Issue by Kri-U** [Infomaniak/desktop-kDrive#250]
**Description**
when the app is syncing, it only uses one core at 100%. This is likely to heat up the system unnecessarily. the core

**Steps to reproduce**
1. set up a synchronization client where it has to synchronize some files (preferably bigger ones)
2. start the synchronization
3. see the CPU usage when it starts transferring

**Expected behavior**
The synchronization should distribute its processing needs on several cores to avoid having only one or a few cores at 100%.

**Screenshots**
![image](https://github.com/user-attachments/assets/0fb43bf3-0ec3-46d6-afca-fdbef1a716dc)

**Additional context**
I'm on OpenSUSE TumbleWeed 20240808 64 bits, KDE Plasma 6.1.4, Kernel 6.10.3-1
this bug did not appear with a system or KDE update

**Comment by luc-guyot-infomaniak** [comment]
Thanks for your report. The behavior you have described in your issue can indeed be reproduced on a Linux system.
Coming back to you soon with our thoughts about it.

**Comment by beankylla** [comment]
This put together with bug 404 sometimes made my computer security shutdown (overpowered laptop with allegedly insufficient cooling but it's still the only program to do so, even games with graphic rendering do not have this consequence)

**Comment by luc-guyot-infomaniak** [comment]
@Kri-U Our implementation of parallel file downloads and file uploads (see the`JobManager` configuration) is rather conservative in terms of the number of jobs that can actually run in parallel. Admittedly, this is not optimal and it deserves a second thought. We plan to profile the application and enhance performance, but this does not belong to our immediate roadmap. I have recorded an issue in our development backlog to track our progress on this topic. Suggestions are of course welcome.

@beankylla It would be very nice if you could share your logs so that we can relate specific tasks of the synchronization engine with abnormal resource consumption.
